### ISSUE TITLE
why we need Rotate 90 degree

### ISSUE THREAD

**Issue by HiAleeYang** [amin-asdzdh/ExcPose2D#1]
thank you for your work! 
I am also training  HRNet on custom dataset. I don't know why we need the Rotate 90_cc operation.
I adapt your code and change the dataset file.But when I finished training, I infere same example. I suprvisly find the x,y data is inversed.

https://github.com/amin-asdzdh/ExcPose2D/blob/ad4d226b07ef456966c4c9eebec1242d4fddc6d9/misc/transforms.py#L39

**Comment by amin-asdzdh** [comment]
Hi HiAleeYang, you're right, you don't need to rotate 90 degrees, you can bypass this step
 
This is specific to my application, I have done this because the aspect ratio of my dataset didn't agree with the input size of HRNet. So I rotated the samples to minimize information loss when rescaled
